spring.main.register-shutdown-hook: false

homer:
  discord.token: "<TOKEN>"
  intro:
    - username: "<USERNAME>"
      file: "<FILE.mp3>"
    - username: "<USERNAME>"
      file: "<FILE.mp3>"
  reactions:
    - name: "<REACTION_NAME>"
      file: "<FILE.mp3>"
      emoji: "<EMOJI>"
      description: "<DESCRIPTION>"

logging.config: "<logback.xml>"